<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Strict //EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<title>add a review</title>
<style type="text/css">
body {
  font-family:verdana,geneva,arial,sans-serif;
  background-color : #ffffff;
  text-align : center;
}

h1 {
  font-size : 16px;
  font-weight:bold;
}

h2 {
  font-size : 14px;
  font-weight:bold;
}

p {
  font-size : 12px;
}

a {
  color : #866A83;
  font-weight : bold;
  text-decoration : none;
}

a:hover {
  color : #666633;
  text-decoration : underline;
}

#forms {
  width : 600px;
padding-top: 20px;
  padding-left: 20px;
  border : 1px solid thistle;
  margin-left : auto;
  margin-right :auto;
  text-align : left;
}

.formtext {
  font-size : 11px;
  font-weight : bold;
}

.forminput {
font-family : verdana,geneva,arial,sans-serif;
  font-size : 14px;
}

</style>

<script language="JavaScript">
function popener(fileName,windowName) {
    window.name = "hello";
    window.open(fileName,windowName,'directories=false,height=350,width=435,menubar=false,resizeable=false,status=true,toolbar=false');
}

function closeDown() {
    window.opener.location.reload();
    window.close();
}
</script>

</head>
<body>
<h1>Booklist Admin</h1>
<div id="forms">
