<p><strong>add</strong><br>
<a href="<?= $addfile ?>?action=author">an author</a> | <a href="<?= $addfile ?>?action=review">a review</a></p>

<p><strong>edit</strong><br>
<a href="<?= $editfile ?>?action=author">an author</a> | <a href="<?= $editfile ?>?action=review">a review</a></p>


<!-- <p><strong>database</strong><br>
<a href="<?= $actfile ?>?action=dbstop">update database to add stopwords.</a></p> -->
